<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BankAccount extends Model
{
   protected $table = 'bank_account';
   public static $bankNames= [""=>"Select Bank","ALBARAKA BANK (PAKISTAN) LIMITED"=>"ALBARAKA BANK (PAKISTAN) LIMITED",
        "ALLIED BANK LIMITED"=>"ALLIED BANK LIMITED",
        "ASKARI BANK LIMITED"=>"ASKARI BANK LIMITED",
        "BANK AL HABIB LIMITED"=>"BANK AL HABIB LIMITED",
        "BANK ALFALAH LIMITED"=>"BANK ALFALAH LIMITED",
        "BANK ISLAMI PAKISTAN LIMITED"=>"BANK ISLAMI PAKISTAN LIMITED",
        "BURJ BANK LIMITED"=>"BURJ BANK LIMITED",
        "DUBAI ISLAMIC BANK"=>"DUBAI ISLAMIC BANK",
        "FAYSAL BANK LIMITED"=>"FAYSAL BANK LIMITED",
        "FIRST WOMEN BANK LIMITED"=>"FIRST WOMEN BANK LIMITED",
        "HABIB BANK LIMITED"=>"HABIB BANK LIMITED",
        "HABIB METROPOLITAN BANK LIMITED"=>"HABIB METROPOLITAN BANK LIMITED",
        "JS BANK LIMITED"=>"JS BANK LIMITED",
        "KASB BANK LIMITED"=>"KASB BANK LIMITED",
        "MCB BANK LIMITED"=>"MCB BANK LIMITED",
        "MCB ISLAMIC BANK"=>"MCB ISLAMIC BANK",
        "MEEZAN BANK LIMITED"=>"MEEZAN BANK LIMITED",
        "NATIONAL BANK OF PAKISTAN"=>"NATIONAL BANK OF PAKISTAN",
        "NIB BANK LIMITED"=>"NIB BANK LIMITED",
        "SAMBA BANK LIMITED"=>"SAMBA BANK LIMITED",
        "SILK BANK LIMITED"=>"SILK BANK LIMITED",
        "SIND BANK LIMITED"=>"SIND BANK LIMITED",
        "SONERI BANK LIMITED"=>"SONERI BANK LIMITED",
        "STANDARD CHARTERED BANK (PAKISTAN) LIMITED"=>"STANDARD CHARTERED BANK (PAKISTAN) LIMITED",
        "SUMMIT BANK LIMITED"=>"SUMMIT BANK LIMITED",
        "THE BANK OF KHYBER"=>"THE BANK OF KHYBER",
        "THE BANK OF PUNJAB"=>"THE BANK OF PUNJAB",
        "UNITED BANK LIMITED"=>"UNITED BANK LIMITED"];
}
